/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        brand: '#CE2029',
        'brand-strong': '#A61A23',
        'brand-soft': '#FCE8E9',
        primary: '#CE2029',
        'primary-dark': '#A61A23',
        'on-primary': '#FFFFFF',
        'primary-container': '#FFD9DD',
        'on-primary-container': '#3F0006',
        secondary: '#1F1F1F',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#F2F2F2',
        'on-secondary-container': '#151515',
        tertiary: '#8C1D18',
        'on-tertiary': '#FFFFFF',
        background: '#FFFFFF',
        'on-background': '#111111',
        surface: '#FFFFFF',
        'surface-dim': '#F5F5F5',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FAFAFA',
        'surface-container': '#F4F4F5',
        'surface-container-high': '#EEEEF0',
        'surface-container-highest': '#E8E8EA',
        'surface-variant': '#E6D6D6',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#514343',
        outline: '#9E8D8D',
        'outline-variant': '#D8C3C3',
        'inverse-surface': '#2B1F1F',
        'inverse-on-surface': '#FBEDEE',
        'inverse-primary': '#FFB3B8',
        scrim: 'rgba(0, 0, 0, 0.5)',
        shadow: '#000000',
        'neutral-black': '#111111',
        'neutral-white': '#FFFFFF',
        'neutral-gray': '#E6E0E0',
      },
      fontFamily: {
        heading: ['Poppins', 'Montserrat', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        full: '9999px',
      },
      boxShadow: {
        subtle: '0 1px 3px rgba(32, 26, 25, 0.12), 0 1px 2px rgba(32, 26, 25, 0.08)',
        'red-glow': '0 4px 14px rgba(186, 26, 26, 0.18), 0 2px 6px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
        'count-up': 'count-up 0.8s ease-out forwards',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'count-up': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      transitionTimingFunction: {
        'out': 'cubic-bezier(0, 0, 0.2, 1)',
      },
      transitionDuration: {
        '150': '150ms',
        '250': '250ms',
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '2rem',
          lg: '4rem',
          xl: '5rem',
          '2xl': '6rem',
        },
        screens: {
          sm: '640px',
          md: '768px',
          lg: '1024px',
          xl: '1280px',
          '2xl': '1400px',
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
